champcy/farnet-dev

tests/features/farnet_cooperation_call.feature

Fix Behat on farnet_cooperation_call

---

build.farnet.xml

Behat: add clear cache target

---

tests/features/farnet_gp_short_story.feature

Behat: fix error for "field_flag[und][]" not found

---

tests/features/farnet_factsheet_flag.feature
tests/features/farnet_gp_method.feature

Fix behat scenario for the missing label field on error message
MULTISITE-12060

Fix behat scenario

---

lib/features/farnet_core/farnet_core.module

Fix url aliasing in node push

---

lib/modules/farnet_error/farnet_error.module

Add fallback value on the farnet error pages

---

lib/features/farnet_views/farnet_views.module

MULTISITE-12667: Fix the Filter Criteria "Publication channels" on view farnet_view_news

Fix view farnet_view_news

---

lib/modules/farnet_location/farnet_location.module
tests/features/bootstrap/FeatureContext.php
tests/features/farnet_gp_method.feature

Add error handling for farnet location and GeoNames

---

lib/features/farnet_core/farnet_core.install

Added link to base breadcrumb

---

lib/features/farnet_taxonomy/farnet_taxonomy.install

Rework taxonomy parent association to fix alias problems

---

lib/features/farnet_social_media/farnet_social_media.strongarm.inc

Add pinterest link on the social media block.
MULTISITE-12698

Update social media block

---

lib/features/farnet_organisation/farnet_organisation.field_group.inc
lib/features/farnet_organisation/farnet_organisation.info

Add 'Postal address' group in the organisation CT

---

lib/features/farnet_cooperation_ms_fiche/farnet_cooperation_ms_fiche.field_group.inc

'Taxonomy' group field is displayed as a vertical tab

---

lib/features/farnet_social_media_share/farnet_social_media_share.features.fe_block_settings.inc

"Farnet Social Links to Share" block moved

---

lib/features/farnet_cooperation_call/farnet_cooperation_call.features.field_instance.inc
lib/features/farnet_cooperation_idea/farnet_cooperation_idea.features.field_instance.inc
lib/features/farnet_cooperation_ms_fiche/farnet_cooperation_ms_fiche.features.field_instance.inc

'Theme' allows multiple selection

---

lib/features/farnet_communities/farnet_communities.info
lib/features/farnet_communities/farnet_communities.module
lib/features/farnet_communities/farnet_communities.strongarm.inc

Fix node push to public site

---

README.md
build.package.xml
build.test.xml
build.xml
composer.json
docs/developer-guide.md
docs/upgrading.md
lib/features/farnet_user/farnet_user.module
resources/build.custom.xml
resources/composer.json
resources/composer.lock
resources/site.make.example

Merged master back and removed autoloader, now included in the subsite starterkit.

Remove autoload

---

lib/features/farnet_factsheet_flag/farnet_factsheet_flag.features.field_base.inc
lib/modules/farnet_location/farnet_location.module
lib/modules/farnet_location/js/farnet_location.js

Remove the link between region and area in farnet location

---

lib/features/farnet_social_media/farnet_social_media.strongarm.inc

Replace pinterest by instagram in social links

---

lib/features/farnet_maps/farnet_maps.module

Fix maps country coordinates retrieval

---

lib/features/farnet_core/farnet_core.module

use hook_menu_alter to fix that

MULTISITE-13895
